name: CI

permissions:
  contents: read

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Code standards & build
    runs-on: ubuntu-latest
    timeout-minutes: 8

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Checking code format
        run: pnpm run format:check

      - name: Type check
        run: pnpm run typecheck

      - name: Cache OG Images
        uses: actions/cache@v4
        with:
          path: .astro-cache
          key: ${{ runner.os }}-og-images-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-og-images-

      - name: Build
        run: pnpm run build
